include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

default:
  image: ghcr.io/astral-sh/uv:0.9.18-python3.12-bookworm-slim
  tags:
    - DOCKER-AARCH64

variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY
  UV_LINK_MODE: copy
  UV_LOCKED: 'true'

build-mkdocs:
  stage: test
  script:
    - uv run mkdocs build --strict ${CI_MERGE_REQUEST_IID+--no-directory-urls}
  artifacts:
    expire_in: 3h
    paths:
      - site/

.deploy-mkdocs:
  variables:
    # We only need the artifacts from the build-mkdocs job -> no need to clone the repository
    GIT_STRATEGY: none
  dependencies:
    - build-mkdocs
  stage: deploy
  image: busybox:1.37.0
  script:
    - mv site/ public/
  artifacts:
    paths:
      - public/

review:
  extends: .deploy-mkdocs
  after_script:
    - |
      printArtifactsUrl() {
        # Warning: wildcard SSL cert will fail if subdomain contains a dot, like in
        # personal repos if your username has a dot. Do not use personal repos
        # for anything remotely serious, create a Gitlab group instead.
        SUBDOMAIN="$CI_PROJECT_ROOT_NAMESPACE"

        # Support artifacts path for Gitlab subgroups, trim
        # CI_PROJECT_ROOT_NAMESPACE from CI_PROJECT_PATH.
        PATH="${CI_PROJECT_PATH#${CI_PROJECT_ROOT_NAMESPACE}/}"

        echo "https://${SUBDOMAIN}.${CI_PAGES_DOMAIN}/-/${PATH}/-/jobs/${CI_JOB_ID}/artifacts"
      }
    - REVIEW_URL="$(printArtifactsUrl)/public/index.html"
    - echo "REVIEW_URL=$REVIEW_URL" >> review.env
  artifacts:
    reports:
      dotenv: review.env
  environment:
    name: review/${CI_MERGE_REQUEST_PROJECT_PATH}/${CI_MERGE_REQUEST_IID}
    url: $REVIEW_URL
  rules:
    - if: '$CI_MERGE_REQUEST_IID'

pages:
  extends: .deploy-mkdocs
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
