site_name: Password reset

theme:
  name: 'code-siemens-code-docs-theme'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: siemens/element/element-theme-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: siemens/element/element-sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: siemens/element/element-economy
        name: Switch to system theme

nav:
  - Home:
    - Password reset: index.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      guess_lang: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.blocks.admonition
  - footnotes
  - pymdownx.blocks.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
